CREATE database springdb;
Use springdb;

-- Create Table
CREATE TABLE APP_USER(
	USER_ID BIGINT NOT NULL,
    USER_NAME VARCHAR(36) NOT NULL,
    ENCRYPTED_PASSWORD VARCHAR(128) NOT NULL,
    ENABLED BIT NOT NULL
);

--
ALTER TABLE APP_USER
  ADD constraint APP_USER_PK primary key(USER_ID);

ALTER TABLE APP_USER
  ADD constraint APP_USER_UK unique(USER_NAME);

-- ALTER TABLE APP_USER RENAME COLUMN ENABLE TO ENABLED;
  
-- Create Table
CREATE TABLE APP_ROLE(
	ROLE_ID BIGINT NOT NULL,
    ROLE_NAME VARCHAR(30) NOT NULL
);

ALTER TABLE APP_ROLE
  ADD constraint APP_ROLE_PK primary key(ROLE_ID);
  
ALTER TABLE APP_ROLE
  ADD constraint APP_ROLE_UK unique(ROLE_NAME);
  
-- Create Table
CREATE TABLE USER_ROLE(
	ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL
);

ALTER TABLE USER_ROLE
  ADD constraint USER_ROLE_PK primary key(ID);

ALTER TABLE USER_ROLE
  ADD constraint USER_ROLE_UK unique(USER_ID, ROLE_ID);
  
ALTER TABLE USER_ROLE
  ADD constraint USER_ROLE_FK1 foreign key(USER_ID) references APP_USER(USER_ID);

ALTER TABLE USER_ROLE
  ADD constraint USER_ROLE_FK2 foreign key(ROLE_ID) references APP_ROLE(ROLE_ID);

-- Create Table, Used by Spring Remember Me API

CREATE TABLE PERSISTENT_LOGINS(
	USERNAME VARCHAR(64) NOT NULL,
    SERIES VARCHAR(64) NOT NULL,
    TOKEN VARCHAR(64) NOT NULL,
    LAST_USED TIMESTAMP NOT NULL,
    PRIMARY KEY(SERIES)
);

INSERT INTO APP_USER(USER_ID, USER_NAME, ENCRYPTED_PASSWORD, ENABLED) 
  VALUES(1, 'dbadmin1', '$2a$10$EfrmD14NcjpE3XZ7dBfuTO4EvqvU/V/ngozzyc8g8n8B.TInXDVOO', 1);
  
INSERT INTO APP_USER(USER_ID, USER_NAME, ENCRYPTED_PASSWORD, ENABLED) 
  VALUES(2, 'dbuser1', '$2a$10$.UOCAhLyuBlVl.i13KgTj.ZHfzpfzjMQ1rgBAayLWuBPV6kE2.w9G', 1);

INSERT INTO APP_ROLE(ROLE_ID, ROLE_NAME) VALUES(1, 'ROLE_ADMIN');

INSERT INTO APP_ROLE(ROLE_ID, ROLE_NAME) VALUES(2, 'ROLE_USER');

INSERT INTO USER_ROLE(ID, USER_ID, ROLE_ID) VALUES(1, 1, 1); 
INSERT INTO USER_ROLE(ID, USER_ID, ROLE_ID) VALUES(2, 1, 2); 
INSERT INTO USER_ROLE(ID, USER_ID, ROLE_ID) VALUES(3, 2, 2); 
