##
# Data Source Configuration
##

##
# Profile Configuration
# available profiles: dev, prod
##

##Hibernate - Jpa configuation
spring:
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
  profiles:
    active: dev
    

server:
  servlet:
    context-path: /api
    
